name: 'Narakeet'
description: 'Build videos directly from GitHub repositories using Narakeet'
inputs:
  github-token:
    description: 'GitHub action Authentication Token'
    required: true
  api-key:
    description: 'Narakeet API Key'
    required: true
  source-path:
    description: 'Relative path to the main video source file (.yaml or .json)'
    required: true
  api-url:
    description: '(optional) override for the API URl'
    required: false
  result-file:
    description: '(optional) Local file system path for the result file'
    required: false
outputs:
  video-url:
    description: 'Temporary video URL - valid for 10 minutes'
  video-file:
    description: 'Resulting video file, ready for uploading to artifacts or further processing'
  poster-url:
    description: 'Temporary poster image URL - valid for 10 minutes'
  poster-file:
    description: 'Resulting poster image file, ready for uploading to artifacts or further processing'
  srt-url:
    description: 'Temporary subtitle (.srt) URL - valid for 10 minutes. Only set if video produces external subtitles.'
  srt-file:
    description: 'Resulting subtitle (.srt) file, ready for uploading to artifacts or further processing. Only set if video produces external subtitles.'
  vtt-url:
    description: 'Temporary subtitle (.vtt) URL - valid for 10 minutes. Only set if video produces external subtitles.'
  vtt-file:
    description: 'Resulting subtitle (.vtt) file, ready for uploading to artifacts or further processing. Only set if video produces external subtitles.'
runs:
  using: 'node18'
  main: 'dist/action.js'
branding:
  icon: 'video'
  color: 'blue'

